let CFG,state={values:{},notes:{},flags:{},photos:{},sketch:{strokes:[],background:'',viewport:{scale:1,x:0,y:0}},activeTab:'Property'};
const STORAGE_KEY='clipboard-v4-3-2-state';const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){
  CFG=await fetch('config.json?v=4.3.2',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`Unable to load config.json (${r.status})`);return r.json()});
  const defaults={};
  [...CFG.app,...CFG.followups].forEach(f=>{if(f['Default Value']!==undefined&&f['Default Value']!=='')defaults[f['Field ID']]=f['Default Value']});
  const saved=localStorage.getItem(STORAGE_KEY)||localStorage.getItem('clipboard-v4-3-state')||localStorage.getItem('clipboard-v4-2-1-state')||localStorage.getItem('clipboard-v4-1-state')||localStorage.getItem('clipboard-v4-state');
  if(saved){try{const parsed=JSON.parse(saved);state={...state,...parsed,values:{...defaults,...(parsed.values||{})},notes:parsed.notes||{},flags:parsed.flags||{},photos:parsed.photos||{},sketch:parsed.sketch||{strokes:[],background:'',viewport:{scale:1,x:0,y:0}}}}catch(e){state.values={...defaults}}}
  else state.values={...defaults};
  $('#brand').textContent=CFG.settings['App Name']||'Clipboard';
  $('#version').textContent=CFG.settings.Version||'4.3.2';
  buildTabs();render();updateCounters();$('#saveBtn').onclick=save;
}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#saveBtn').textContent='✓';setTimeout(()=>$('#saveBtn').textContent='💾',700)}function optionsFor(ref){if(!ref)return[];if(CFG.lists[ref])return CFG.lists[ref];return String(ref).split(/[,;|]/).map(x=>x.trim()).filter(Boolean)}function truth(v){return['yes','true','1','enabled'].includes(String(v??'').toLowerCase())||v===true}
function normalizeValue(v){return Array.isArray(v)?v.map(x=>String(x).trim()):String(v??'').trim()}
function compareValues(actual,operator,expected){
  const a=normalizeValue(actual),e=String(expected??'').trim();
  const equal=Array.isArray(a)?a.includes(e):a===e;
  if(operator==='='||operator==='==')return equal;
  if(operator==='!='||operator==='<>')return !equal;
  const an=Number(Array.isArray(a)?a[0]:a),en=Number(e);
  if(Number.isNaN(an)||Number.isNaN(en))return false;
  if(operator==='>')return an>en;if(operator==='<')return an<en;if(operator==='>=')return an>=en;if(operator==='<=')return an<=en;
  return false;
}
function evaluateClause(clause){
  const text=String(clause||'').trim().replace(/^\((.*)\)$/,'$1').trim();
  const m=text.match(/^([^=!<>]+?)\s*(>=|<=|<>|!=|==|=|>|<)\s*(.*?)$/);
  if(!m)return false;
  return compareValues(state.values[m[1].trim()],m[2],m[3].trim());
}
function ruleVisible(rule){
  const text=String(rule??'').trim();
  if(!text||/^always$/i.test(text))return true;
  return text.split(/\s*(?:\|\||OR)\s*/i).some(orPart=>orPart.split(/\s*(?:&&|AND)\s*/i).every(evaluateClause));
}
function clearHiddenValues(){
  let changed=false;
  [...CFG.app,...CFG.followups].forEach(f=>{const id=f['Field ID'];if(id&&f['Visibility Rule']&&!ruleVisible(f['Visibility Rule'])&&Object.prototype.hasOwnProperty.call(state.values,id)){delete state.values[id];changed=true}});
  return changed;
}
function buildTabs(){let nav=CFG.navigation||[];if(!nav.includes('Sketch'))nav.splice(Math.max(0,nav.length-1),0,'Sketch');if(!nav.includes('Exit Interview'))nav.splice(Math.max(0,nav.length-1),0,'Exit Interview');$('#tabs').innerHTML=nav.map(t=>`<button class="tab ${state.activeTab===t?'active':''}" data-tab="${esc(t)}">${esc(t)}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;buildTabs();render();scrollTo(0,0)})}
function hasMeaningfulValue(v){return v!==undefined&&v!==null&&v!==''&&!(Array.isArray(v)&&!v.length)&&v!==false&&String(v).toLowerCase()!=='no'&&Number(v)!==0}
function followTriggerMatches(f,v){
  if(!hasMeaningfulValue(v))return false;
  const group=String(f['Follow-Up Group']||'').toLowerCase(),text=(Array.isArray(v)?v.join(' '):String(v)).toLowerCase();
  if(group==='well')return text.includes('well');
  if(group==='septic')return text.includes('septic');
  if(group==='pud'||group==='hoa'||group==='pool'||group==='solar'||group.includes('garage conversion')||group.includes('addition')||group.includes('detached')||group.includes('fireplace')||group.includes('dock'))return truth(v)||!['no','none','not present','0'].includes(text);
  return true;
}
function activeFollowGroups(){let groups=new Set(['General']);CFG.app.forEach(f=>{if(truth(f['Trigger Follow-Up'])&&f['Follow-Up Group']){let v=state.values[f['Field ID']];if(followTriggerMatches(f,v))groups.add(f['Follow-Up Group'])}});return groups}
function rowsForTab(tab){if(tab==='Exit Interview'){let groups=activeFollowGroups();return CFG.followups.filter(f=>groups.has(f['Follow-Up Group'])&&ruleVisible(f['Visibility Rule'])).sort((a,b)=>{const ga=CFG.followups.findIndex(x=>x['Follow-Up Group']===a['Follow-Up Group']),gb=CFG.followups.findIndex(x=>x['Follow-Up Group']===b['Follow-Up Group']);return ga-gb||Number(a['Display Order']||999)-Number(b['Display Order']||999)})}return CFG.app.filter(f=>f.Tab===tab&&truth(f.Visible??'Yes')&&ruleVisible(f['Visibility Rule'])).sort((a,b)=>Number(a['Display Order']||999)-Number(b['Display Order']||999))}
function updateCounterVisibility(){const bar=$('#counterbar');if(bar)bar.hidden=!['Interior','Sketch','Exit Interview','Review'].includes(state.activeTab)}
function render(){updateCounterVisibility();if(state.activeTab==='Sketch')return renderSketch();if(state.activeTab==='Review')return renderReview();let rows=rowsForTab(state.activeTab),groupKey=state.activeTab==='Exit Interview'?'Follow-Up Group':'Section',html='',last='';for(const f of rows){let sec=f[groupKey]||'General';if(sec!==last){html+=`<h2 class="section-title">${esc(sec)}</h2>`;last=sec}html+=fieldHtml(f)}if(!html)html='<div class="empty">No fields are configured for this tab yet.</div>';$('#screen').innerHTML=html;wireFields()}
function fieldHtml(f){let id=f['Field ID'],val=state.values[id],req=truth(f.Required),flagged=state.flags[id];return`<section class="field ${req?'required':''} ${flagged?'flagged':''}" data-id="${esc(id)}"><div class="labelrow"><div class="label">${esc(f['Field Label']||f.Question)}</div><div class="tools"><button class="iconbtn noteBtn ${state.notes[id]?'active':''}" title="Add note">📝</button><label class="iconbtn" title="Add photo">📷<input class="photo-input" type="file" accept="image/*" capture="environment" multiple></label><button class="iconbtn flagBtn ${flagged?'active':''}" title="Flag for review">⚑</button></div></div><div class="control">${controlHtml(f,val)}</div><div class="note ${state.notes[id]!==undefined?'open':''}"><textarea class="noteText" placeholder="Note for this field">${esc(state.notes[id]||'')}</textarea></div><div class="photo-count">${(state.photos[id]||[]).length?`${state.photos[id].length} photo(s) attached`:''}</div></section>`}
function controlHtml(f,val){let type=f['Input Type'],opts=optionsFor(f.Options);if(type==='LongText')return`<textarea class="value" placeholder="Enter details">${esc(val||'')}</textarea>`;if(type==='Text'||type==='Currency')return`<input class="value" type="${type==='Currency'?'number':'text'}" value="${esc(val??'')}" ${type==='Currency'?'step="0.01"':''}>`;if(type==='Date'||type==='Time')return`<input class="value" type="${type.toLowerCase()}" value="${esc(val??'')}">`;if(type==='Dropdown')return`<select class="value"><option value="">Select…</option>${opts.map(o=>`<option value="${esc(o)}" ${String(val)===String(o)?'selected':''}>${esc(o)}</option>`).join('')}</select>`;if(type==='Button'||type==='Toggle'||type==='Rating')return`<div class="choices ${type==='Toggle'?'toggle':''}">${(opts.length?opts:(type==='Toggle'?['Yes','No']:[])).map(o=>`<button class="choice ${String(val)===String(o)?'selected':''}" data-choice="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;if(type==='MultiSelect')return`<div class="choices">${opts.map(o=>`<button class="choice ${(Array.isArray(val)&&val.includes(o))?'selected':''}" data-multi="${esc(o)}">${esc(o)}</button>`).join('')}</div>`;if(type==='Checkbox')return`<label><input class="checkValue" type="checkbox" ${truth(val)?'checked':''}> Yes</label>`;if(type==='Counter')return`<div class="counter"><button data-delta="-1">−</button><output>${Number(val||0)}</output><button data-delta="1">+</button></div>`;if(type==='Camera')return`<label class="action secondary">Add photo<input class="photo-input valuePhoto" type="file" accept="image/*" capture="environment" multiple></label>`;if(type==='Sketch')return`<button class="action secondary openSketch">Open Sketch Workspace</button>`;return`<input class="value" type="text" value="${esc(val??'')}">`}
function wireFields(){document.querySelectorAll('.field').forEach(el=>{let id=el.dataset.id,input=el.querySelector('.value');if(input)input.oninput=()=>{state.values[id]=input.value;save()};let check=el.querySelector('.checkValue');if(check)check.onchange=()=>{state.values[id]=check.checked;changed()};el.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{state.values[id]=b.dataset.choice;changed(true)});el.querySelectorAll('[data-multi]').forEach(b=>b.onclick=()=>{let a=Array.isArray(state.values[id])?[...state.values[id]]:[],x=b.dataset.multi;a.includes(x)?a.splice(a.indexOf(x),1):a.push(x);state.values[id]=a;changed(true)});el.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>{state.values[id]=Math.max(0,Number(state.values[id]||0)+Number(b.dataset.delta));changed(true)});el.querySelector('.noteBtn').onclick=()=>{let n=el.querySelector('.note');n.classList.toggle('open');if(n.classList.contains('open')&&state.notes[id]===undefined)state.notes[id]=''};el.querySelector('.noteText').oninput=e=>{state.notes[id]=e.target.value;save()};el.querySelector('.flagBtn').onclick=()=>{state.flags[id]=!state.flags[id];changed(true)};el.querySelectorAll('.photo-input').forEach(inp=>inp.onchange=()=>{state.photos[id]=[...(state.photos[id]||[]),...Array.from(inp.files).map(f=>({name:f.name,size:f.size,type:f.type}))];changed(true)});let os=el.querySelector('.openSketch');if(os)os.onclick=()=>{state.activeTab='Sketch';buildTabs();render();scrollTo(0,0)}})}
function changed(r=false){clearHiddenValues();updateCounters();save();if(r)render()}function updateCounters(){[['liveBeds','bedroom_count'],['liveFull','full_bath_count'],['liveHalf','half_bath_count'],['liveSmoke','smoke_co_count']].forEach(([a,b])=>$('#'+a).textContent=Number(state.values[b]||0))}

let sketchTool='freehand',sketchUndo=[],sketchRedo=[],sketchPointer=null;
function ensureSketch(){if(!state.sketch)state.sketch={};state.sketch.strokes=state.sketch.strokes||[];state.sketch.background=state.sketch.background||'';state.sketch.viewport=state.sketch.viewport||{scale:1,x:0,y:0};return state.sketch}
function sketchSnapshot(){return JSON.parse(JSON.stringify(ensureSketch()))}
function pushSketchHistory(){sketchUndo.push(sketchSnapshot());if(sketchUndo.length>40)sketchUndo.shift();sketchRedo=[]}
function setSketchTool(tool){sketchTool=tool;document.querySelectorAll('[data-sketch-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.sketchTool===tool));const c=$('#sketchCanvas');if(c)c.style.cursor=tool==='eraser'?'cell':tool==='pan'?'grab':'crosshair';const st=$('#sketchToolStatus');if(st)st.textContent='Tool: '+tool}
function renderSketch(){const s=ensureSketch();$('#screen').innerHTML=`<h2 class="section-title">Manual Sketch</h2><div class="sketch-card"><div class="sketch-toolbar"><button class="choice" data-sketch-tool="freehand">✏️ Freehand</button><button class="choice" data-sketch-tool="line">📏 Wall</button><button class="choice" data-sketch-tool="rect">▭ Rectangle</button><button class="choice" data-sketch-tool="eraser">🧽 Eraser</button><button class="choice" data-sketch-tool="pan">✋ Pan</button></div><div class="sketch-toolbar"><button class="action secondary" id="undoSketch">↶ Undo</button><button class="action secondary" id="redoSketch">↷ Redo</button><button class="action secondary" id="zoomOutSketch">− Zoom</button><button class="action secondary" id="zoomInSketch">+ Zoom</button><button class="action secondary" id="fitSketch">Fit</button></div><div class="sketch-toolbar"><label class="action secondary">Import Background<input id="sketchBackgroundInput" type="file" accept="image/*" hidden></label><button class="action secondary" id="clearSketch">Clear Drawing</button><button class="action secondary" id="removeBackground">Remove Background</button></div><div class="sketch-stage" id="sketchStage"><div class="sketch-viewport" id="sketchViewport">${s.background?`<img class="sketch-background" id="sketchBackground" src="${s.background}" alt="Imported sketch background">`:''}<canvas id="sketchCanvas"></canvas></div></div><div class="small sketch-status"><span id="sketchToolStatus">Tool: ${sketchTool}</span> • <span id="sketchZoomStatus">Zoom: ${Math.round(s.viewport.scale*100)}%</span> • Auto-saved</div></div>`;bindSketch();setSketchTool(sketchTool)}
function bindSketch(){const s=ensureSketch(),stage=$('#sketchStage'),canvas=$('#sketchCanvas');if(!stage||!canvas)return;const resize=()=>{const r=stage.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width));canvas.height=Math.max(500,Math.round(r.height));drawSketch();applySketchTransform()};resize();window.addEventListener('resize',resize,{once:true});
 const pos=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left),y:(e.clientY-r.top)}};
 const local=p=>({x:(p.x-s.viewport.x)/s.viewport.scale,y:(p.y-s.viewport.y)/s.viewport.scale});
 const nearest=p=>{let best=-1,dist=18/s.viewport.scale;s.strokes.forEach((st,i)=>{(st.points||[]).forEach(q=>{const d=Math.hypot(q.x-p.x,q.y-p.y);if(d<dist){dist=d;best=i}})});return best};
 stage.onpointerdown=e=>{e.preventDefault();stage.setPointerCapture(e.pointerId);const p=pos(e),lp=local(p);if(sketchTool==='freehand'){pushSketchHistory();const stroke={type:'freehand',width:4,points:[lp]};s.strokes.push(stroke);sketchPointer={id:e.pointerId,type:'freehand',stroke}}else if(sketchTool==='line'||sketchTool==='rect'){pushSketchHistory();const stroke={type:sketchTool,width:4,points:[lp,lp]};s.strokes.push(stroke);sketchPointer={id:e.pointerId,type:sketchTool,stroke}}else if(sketchTool==='eraser'){const i=nearest(lp);if(i>=0){pushSketchHistory();s.strokes.splice(i,1);drawSketch();save()}}else if(sketchTool==='pan'){sketchPointer={id:e.pointerId,type:'pan',start:p,x:s.viewport.x,y:s.viewport.y}}};
 stage.onpointermove=e=>{if(!sketchPointer||sketchPointer.id!==e.pointerId)return;e.preventDefault();const p=pos(e),lp=local(p);if(sketchPointer.type==='freehand'){sketchPointer.stroke.points.push(lp);drawSketch()}else if(sketchPointer.type==='line'||sketchPointer.type==='rect'){sketchPointer.stroke.points[1]=lp;drawSketch()}else if(sketchPointer.type==='pan'){s.viewport.x=sketchPointer.x+p.x-sketchPointer.start.x;s.viewport.y=sketchPointer.y+p.y-sketchPointer.start.y;applySketchTransform()}};
 const end=e=>{if(sketchPointer&&sketchPointer.id===e.pointerId){sketchPointer=null;save()}};stage.onpointerup=end;stage.onpointercancel=end;
 document.querySelectorAll('[data-sketch-tool]').forEach(b=>b.onclick=()=>setSketchTool(b.dataset.sketchTool));
 $('#undoSketch').onclick=()=>{if(!sketchUndo.length)return;sketchRedo.push(sketchSnapshot());state.sketch=sketchUndo.pop();save();renderSketch()};$('#redoSketch').onclick=()=>{if(!sketchRedo.length)return;sketchUndo.push(sketchSnapshot());state.sketch=sketchRedo.pop();save();renderSketch()};
 $('#zoomInSketch').onclick=()=>zoomSketch(1.25);$('#zoomOutSketch').onclick=()=>zoomSketch(.8);$('#fitSketch').onclick=()=>{s.viewport={scale:1,x:0,y:0};save();applySketchTransform()};
 $('#clearSketch').onclick=()=>{if(confirm('Clear all manual drawing marks?')){pushSketchHistory();s.strokes=[];save();drawSketch()}};$('#removeBackground').onclick=()=>{if(s.background&&confirm('Remove imported background?')){s.background='';save();renderSketch()}};
 $('#sketchBackgroundInput').onchange=e=>{const f=e.target.files&&e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{s.background=reader.result;save();renderSketch()};reader.readAsDataURL(f)};applySketchTransform();drawSketch()}
function zoomSketch(mult){const s=ensureSketch(),stage=$('#sketchStage');if(!stage)return;const r=stage.getBoundingClientRect(),cx=r.width/2,cy=r.height/2,old=s.viewport.scale,ns=Math.max(.5,Math.min(4,old*mult)),ratio=ns/old;s.viewport.x=cx-(cx-s.viewport.x)*ratio;s.viewport.y=cy-(cy-s.viewport.y)*ratio;s.viewport.scale=ns;save();applySketchTransform()}
function applySketchTransform(){const s=ensureSketch(),v=$('#sketchViewport'),z=$('#sketchZoomStatus');if(v)v.style.transform=`translate(${s.viewport.x}px,${s.viewport.y}px) scale(${s.viewport.scale})`;if(z)z.textContent=`Zoom: ${Math.round(s.viewport.scale*100)}%`}
function drawSketch(){const s=ensureSketch(),c=$('#sketchCanvas');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#d7263d';x.lineCap='round';x.lineJoin='round';for(const st of s.strokes){const pts=st.points||[];if(pts.length<2)continue;x.lineWidth=st.width||4;x.beginPath();if(st.type==='rect'){const a=pts[0],b=pts[1];x.rect(a.x,a.y,b.x-a.x,b.y-a.y)}else{x.moveTo(pts[0].x,pts[0].y);for(const p of pts.slice(1))x.lineTo(p.x,p.y)}x.stroke()}}

function fieldLabel(f){return f['Field Label']||f.Question||f['Field ID']||'Review item'}
function fieldLocation(f){return f.Tab==='Exit Interview'?'Exit Interview':(f.Tab||'Property')}
function goToReviewField(tab,id){state.activeTab=tab;buildTabs();render();scrollTo(0,0);setTimeout(()=>{const el=document.querySelector(`.field[data-id="${CSS.escape(id)}"]`);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('review-focus');setTimeout(()=>el.classList.remove('review-focus'),1800)}},80)}
function reviewItemHtml(item){const cls=item.level==='error'?'review-error':item.level==='warning'?'review-warning':'review-info';const icon=item.level==='error'?'✕':item.level==='warning'?'⚠':'ℹ';return`<button class="review-item ${cls}" data-review-tab="${esc(item.tab)}" data-review-id="${esc(item.id)}"><span class="review-icon">${icon}</span><span class="review-copy"><b>${esc(item.title)}</b><small>${esc(item.reason)}</small><em>${esc(item.tab)}${item.section?' • '+esc(item.section):''}</em></span><span class="review-arrow">›</span></button>`}
function renderReview(){
  let visible=CFG.app.filter(f=>truth(f.Visible??'Yes')&&ruleVisible(f['Visibility Rule']));
  let activeGroups=activeFollowGroups();
  let followVisible=CFG.followups.filter(f=>activeGroups.has(f['Follow-Up Group'])&&ruleVisible(f['Visibility Rule']));
  let allVisible=[...visible,...followVisible];
  let items=[];
  allVisible.forEach(f=>{let id=f['Field ID'],v=state.values[id],empty=v===undefined||v===''||(Array.isArray(v)&&!v.length);if(truth(f.Required)&&empty)items.push({level:'error',id,title:fieldLabel(f),reason:'Required response is incomplete.',tab:fieldLocation(f),section:f.Section||f['Follow-Up Group']||''})});
  allVisible.forEach(f=>{let id=f['Field ID'];if(state.flags[id])items.push({level:'warning',id,title:fieldLabel(f),reason:state.notes[id]&&String(state.notes[id]).trim()?`Flagged: ${String(state.notes[id]).trim()}`:'Flagged during the inspection. Open the item to review or clear the flag.',tab:fieldLocation(f),section:f.Section||f['Follow-Up Group']||''})});
  let notes=Object.values(state.notes).filter(v=>String(v).trim()).length,flags=Object.values(state.flags).filter(Boolean).length,photos=Object.values(state.photos).reduce((a,b)=>a+b.length,0);
  let errors=items.filter(x=>x.level==='error').length,warnings=items.filter(x=>x.level==='warning').length;
  $('#screen').innerHTML=`<h2 class="section-title">Inspection Review</h2><div class="review-summary"><div><b>${errors}</b><span>Incomplete</span></div><div><b>${warnings}</b><span>Flagged</span></div><div><b>${notes}</b><span>Notes</span></div><div><b>${photos}</b><span>Photos</span></div></div>${items.length?`<div class="review-heading"><b>Items requiring review</b><span>Tap an item to open it</span></div><div class="review-items">${items.map(reviewItemHtml).join('')}</div>`:'<div class="success review-complete"><b>✓ Inspection review complete</b><br>No required or flagged items are outstanding.</div>'}<div class="review-card"><b>Inspection totals</b><div class="review-line"><span>Bedrooms</span><b>${Number(state.values.bedroom_count||0)}</b></div><div class="review-line"><span>Full bathrooms</span><b>${Number(state.values.full_bath_count||0)}</b></div><div class="review-line"><span>Half bathrooms</span><b>${Number(state.values.half_bath_count||0)}</b></div><div class="review-line"><span>Smoke / CO detectors</span><b>${Number(state.values.smoke_co_count||0)}</b></div></div><div class="review-card"><b>Exit Interview groups</b><div class="small">${[...activeGroups].map(esc).join(' • ')}</div></div><div class="actions"><button class="action" id="exportBtn">Export JSON</button><button class="action secondary" id="resetBtn">Reset Inspection</button></div>`;
  document.querySelectorAll('[data-review-id]').forEach(b=>b.onclick=()=>goToReviewField(b.dataset.reviewTab,b.dataset.reviewId));
  $('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='clipboard-v4-3-2-inspection.json';a.click();URL.revokeObjectURL(a.href)};
  $('#resetBtn').onclick=()=>{if(confirm('Clear this inspection?')){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem('clipboard-v4-3-state');localStorage.removeItem('clipboard-v4-2-1-state');localStorage.removeItem('clipboard-v4-state');state={values:{},notes:{},flags:{},photos:{},sketch:{strokes:[],background:'',viewport:{scale:1,x:0,y:0}},activeTab:'Property'};[...CFG.app,...CFG.followups].forEach(f=>{if(f['Default Value']!==undefined&&f['Default Value']!=='')state.values[f['Field ID']]=f['Default Value']});buildTabs();render();updateCounters()}}}
init();